-- player_record_detail 테이블 (Season별 상세 스탯)
CREATE TABLE `player_record_detail` (
	`player_record_detail_id`	INT	NOT NULL AUTO_INCREMENT	COMMENT '선수 기록 상세정보ID',
	`player_id`	INT	NOT NULL	COMMENT '선수 ID',
	`season`	YEAR	NULL	COMMENT '시즌연도',
	`games` INT NULL COMMENT '참여게임',
	`ab`	INT	NULL	COMMENT '타자/타수',
	`hit`	INT	NULL	COMMENT '타자/안타 수',
	`1b`	INT	NULL	COMMENT '타자/1루타',
	`2b`	INT	NULL	COMMENT '타자/2루타',
	`3b`	INT	NULL	COMMENT '타자/3루타',
	`hr`	INT	NULL	COMMENT '타자/홈런 수',
	`rbi`	INT	NULL	COMMENT '타자/타점',
	`hitter_so`	INT	NULL	COMMENT '타자/삼진 수',
	`hitter_bb`	INT	NULL	COMMENT '타자/볼넷 수',
	`hbp`	INT	NULL	COMMENT '타자/사구',
	`sf`	INT	NULL	COMMENT '타자/희생플라이',
	`ip`	DECIMAL(4,1)	NULL	COMMENT '투수/이닝 수',
	`er`	INT	NULL	COMMENT '투수/자책점',
	`pitcher_h`	INT	NULL	COMMENT '투수/피안타 수',
	`pitcher_so`	INT	NULL	COMMENT '투수/삼진',
	`pitcher_bb`	INT	NULL	COMMENT '투수/볼넷 허용',
	`win`	INT	NULL	COMMENT '투수/승',
	`lose`	INT	NULL	COMMENT '투수/패',
	`save`	INT	NULL	COMMENT '투수/세이브',
	`error`	INT	NULL	COMMENT '수비/실책',
	`assist`	INT	NULL	COMMENT '수비/어시스트',
	`po`	INT	NULL	COMMENT '수비/풋아웃',
	`sb`	INT	NULL	COMMENT '주루/도루성공',
	`cs`	INT	NULL	COMMENT '주루/도루실패',
	PRIMARY KEY (`player_record_detail_id`),
    UNIQUE KEY (`player_id`,`season`), -- 선수의 동일 시즌 중복금지
	CONSTRAINT `FK_prd_player` FOREIGN KEY (`player_id`) REFERENCES `player` (`player_id`)
);